#!/bin/bash

# This script builds FFmpeg targeting Emscripten and places the built library
# in the root folder of this project.

# No -i to remove need for TTY device (enabling running in GitHub Actions)
docker pull trzeci/emscripten:1.38.45
docker run -t \
    --rm \
    -v $PWD:/src \
    trzeci/emscripten:1.38.45 \
    sh -c '''
    cd /src && \
    emconfigure ./configure \
        --disable-x86asm \
        --disable-inline-asm \
        --disable-doc \
        --disable-gpl \
        --enable-static \
        --disable-shared \
        --disable-stripping \
        --enable-demuxer=image2 \
        --enable-decoder=png \
        --enable-protocol=file \
        --nm="llvm-nm -g" \
        --ar=emar \
        --cc=emcc \
        --cxx=em++ \
        --objcc=emcc \
        --dep-cc=emcc && \
   emmake make -j && \
   rm -rf Emscripten/ && \
   mkdir -p Emscripten/ && \
   cp **/*.a Emscripten/
'''
