# workflows/build-and-publish.yml
#
# Fractal: Build & Publish Fractal FFmpeg
# Build and publish the internal Fractal version of FFmpeg.

name: "Fractal: Build & Publish FFmpeg"

on:
    push:
        branches: [master, phil/ci]
        paths:
            - "!README.md"

jobs:

    build-and-publish-ffmpeg:
        name: Build and Publish FFmpeg for 
        runs-on: ${{ matrix.os }}

        # Platforms to build on/for 
        strategy:
            matrix:
                os: [macos-10.14]
            #    os: [macos-10.14, ubuntu-18.04, windows-2016]

        - name: Checkout git repository
            uses: actions/checkout@v2
            with:
                persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
                fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

        - name: Install Xcode CLI
          run: xcode-select --install

        - name: Install Homebrew
          run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

        - name: Install FFmpeg macOS Dependencies
          run: |
            brew install automake fdk-aac git lame libass libtool libvorbis libvpx \ 
            opus sdl shtool texi2html theora wget x264 x265 xvid nasm

        - name: Configure and Make FFmpeg
          run: |
            ./configure \
            --prefix=/usr/local --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype \
            --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 \ 
            --enable-libopus --enable-libxvid --samples=fate-suite/ \
            make

        # TODO: find where the .dylibs are, zip them and upload them to S3




